### ISSUE TITLE
replace TODO.txt

### ISSUE THREAD

**Issue by epogrebnyak** [ru-corporate/boo#8]
TODO:
- [ ] тест с проверкой свойств отчетности #11 

MAYBE:
- [ ] larger dummy example for tests, 50 + 50 + 1000 example #3
- [ ] писать отдельные файлы: make zip files and save to S3

NOT TODO:
- [ ] silence .loc warning (а где они?)
- [ ] download() can show line count
- [ ] kernel для kaggle
- [ ] проверка размера скачанного файла, риск обрыва данных (`curl -C -`)
- [ ] сделать интерфейс доступа к данным в R
- [ ] описание псевдокода алгоритма `boo`
- [ ] управление проектом через `invoke`

DONE:
- [x] download() must fail on small fail on HTML file
- [x] нет нектороых переменных в whatis #9 
- [x] more subsets, eg SME
- [x] lookup dataframe.util, maybe dataframe.filter
- [x] extend whatis() functionto new coluns
- [x] revive xfailed tests - using temp directory in a fixture with pytest - has get_folder() failure
- [x] global pytest fixture for sample year 0
- [x] test_main.py
- [x] smaller messages.py
- [x] port existing tests fro `sandbox`
- [x] variable descriptions boo.whatis
- [x] boo vs . in backage
- [x] pip install boo
- [x] okved v2
- [x] autopep8
- [x] частичное скачивание по размеру kB 
- [x] тесты Travis CI + coverage 
- [x] сквознные тесты с условным данными `sample`
- [x] более чиcтый вариант логгера (tqdm)
- [x] названия переменных и счетов бухучета в виде справочной функции 
- [x] example.py cleanup
